include:
  - https://cnb.cool/zls-tools/vm/-/blob/main/tools/sync-github-sohaha.yml
  - https://cnb.cool/zls-tools/vm/-/blob/main/rust-ide.yml

$:
  push:
    sync_github:
      env:
          BRANCHS: main
    vscode:
        clouddev:
            imports: https://cnb.cool/zls-tools/env/-/blob/main/envs.yml
            runner:
                tags: cnb:arch:amd64
                cpus: 14