// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FederationThreadStartParams = {
/**
 * Optional stable instance id. When omitted, the server generates one for
 * this process start.
 */
instanceId?: string | null,
/**
 * Display name advertised to other federation peers.
 */
name: string,
/**
 * Optional role label advertised to other federation peers.
 */
role?: string | null,
/**
 * Optional task scope label advertised to other federation peers.
 */
scope?: string | null,
/**
 * Override the federation state root. Defaults to `<CODEX_HOME>/federation`.
 */
stateRoot?: string | null,
/**
 * Optional lease TTL override in seconds. Defaults to 30.
 */
leaseTtlSecs?: number | null, };
