//! Mission 子系统的核心数据结构。

mod error;
mod handoff;
mod knowledge;
mod phases;
mod planner;
mod skill_manager;
mod state;
mod validators;
mod worker_manager;

pub use error::MissionError;
pub use error::MissionResult;
pub use handoff::{CodeReviewResult, FileChange, FileCreation, Handoff, HandoffValidationError, ReviewStatus, UserTestingResult, Verification};
pub use handoff::HANDOFF_EXT;
pub use knowledge::KnowledgeEntry;
pub use knowledge::KnowledgeManager;
pub use knowledge::ServiceDefinition;
pub use knowledge::AGENTS_FILE_NAME;
pub use knowledge::FACTORY_DIR_NAME;
pub use knowledge::LIBRARY_DIR_NAME;
pub use knowledge::SERVICES_FILE_NAME;
pub use phases::MissionPhaseDefinition;
pub use phases::PHASE_DEFINITIONS;
pub use phases::phase_definition;
pub use planner::MissionPlanner;
pub use planner::MissionPlanningStep;
pub use skill_manager::MissionSkillManager;
pub use skill_manager::MISSION_SKILL_FILES;
pub use skill_manager::MISSION_SKILLS_DIR_NAME;
pub use skill_manager::MISSION_SKILLS_WORK_DIR;
pub use state::MISSION_DIR_NAME;
pub use state::MISSION_STATE_FILE_NAME;
pub use state::MissionPhase;
pub use state::MissionPhaseRecord;
pub use state::MissionState;
pub use state::MissionStateStore;
pub use state::MissionStatus;
pub use state::MissionStatusReport;
pub use validators::ScrutinyReport;
pub use validators::ScrutinyStatus;
pub use validators::ScrutinyValidator;
pub use validators::UserTestingReport;
pub use validators::UserTestingValidator;
pub use validators::Validator;
pub use validators::ValidatorConfig;
pub use worker_manager::WorkerManager;
pub use worker_manager::WorkerId;
pub use worker_manager::WorkerInput;
pub use worker_manager::WorkerOutput;
pub use worker_manager::WorkerSession;
pub use worker_manager::WorkerStatus;
pub use worker_manager::HANDOFFS_DIR;
pub use worker_manager::WORKER_SESSIONS_DIR;
