use std::path::PathBuf;
use std::sync::Arc;

use codex_protocol::models::ShellCommandToolCallParams;
use pretty_assertions::assert_eq;

use crate::codex::make_session_and_context;
use crate::exec_env::create_env;
use crate::exec_env::prepend_arg0_helper_dir_to_path;
use crate::is_safe_command::is_known_safe_command;
use crate::powershell::try_find_powershell_executable_blocking;
use crate::powershell::try_find_pwsh_executable_blocking;
use crate::sandboxing::SandboxPermissions;
use crate::shell::Shell;
use crate::shell::ShellType;
use crate::shell_snapshot::ShellSnapshot;
use crate::tools::handlers::ShellCommandHandler;
use std::collections::HashMap;
use tokio::sync::watch;

/// The logic for is_known_safe_command() has heuristics for known shells,
/// so we must ensure the commands generated by [ShellCommandHandler] can be
/// recognized as safe if the `command` is safe.
#[test]
fn commands_generated_by_shell_command_handler_can_be_matched_by_is_known_safe_command() {
    let bash_shell = Shell {
        shell_type: ShellType::Bash,
        shell_path: PathBuf::from("/bin/bash"),
        shell_snapshot: crate::shell::empty_shell_snapshot_receiver(),
    };
    assert_safe(&bash_shell, "ls -la");

    let zsh_shell = Shell {
        shell_type: ShellType::Zsh,
        shell_path: PathBuf::from("/bin/zsh"),
        shell_snapshot: crate::shell::empty_shell_snapshot_receiver(),
    };
    assert_safe(&zsh_shell, "ls -la");

    if let Some(path) = try_find_powershell_executable_blocking() {
        let powershell = Shell {
            shell_type: ShellType::PowerShell,
            shell_path: path.to_path_buf(),
            shell_snapshot: crate::shell::empty_shell_snapshot_receiver(),
        };
        assert_safe(&powershell, "ls -Name");
    }

    if let Some(path) = try_find_pwsh_executable_blocking() {
        let pwsh = Shell {
            shell_type: ShellType::PowerShell,
            shell_path: path.to_path_buf(),
            shell_snapshot: crate::shell::empty_shell_snapshot_receiver(),
        };
        assert_safe(&pwsh, "ls -Name");
    }
}

fn assert_safe(shell: &Shell, command: &str) {
    assert!(is_known_safe_command(
        &shell.derive_exec_args(command, /* use_login_shell */ true)
    ));
    assert!(is_known_safe_command(
        &shell.derive_exec_args(command, /* use_login_shell */ false)
    ));
}

#[tokio::test]
async fn shell_command_handler_to_exec_params_uses_session_shell_and_turn_context() {
    let (session, turn_context) = make_session_and_context().await;

    let command = "echo hello".to_string();
    let workdir = Some("subdir".to_string());
    let login = None;
    let timeout_ms = Some(1234);
    let sandbox_permissions = SandboxPermissions::RequireEscalated;
    let justification = Some("because tests".to_string());

    let expected_command = session.user_shell().derive_exec_args(&command, true);
    let expected_cwd = turn_context.resolve_path(workdir.clone());
    let expected_env = create_env(
        &turn_context.shell_environment_policy,
        Some(session.conversation_id),
    );

    let params = ShellCommandToolCallParams {
        command,
        workdir,
        login,
        timeout_ms,
        sandbox_permissions: Some(sandbox_permissions),
        additional_permissions: None,
        prefix_rule: None,
        justification: justification.clone(),
    };

    let exec_params = ShellCommandHandler::to_exec_params(
        &params,
        &session,
        &turn_context,
        session.conversation_id,
        true,
    )
    .expect("login shells should be allowed");

    // ExecParams cannot derive Eq due to the CancellationToken field, so we manually compare the fields.
    assert_eq!(exec_params.command, expected_command);
    assert_eq!(exec_params.cwd, expected_cwd);
    assert_eq!(exec_params.env, expected_env);
    assert_eq!(exec_params.network, turn_context.network);
    assert_eq!(exec_params.expiration.timeout_ms(), timeout_ms);
    assert_eq!(exec_params.sandbox_permissions, sandbox_permissions);
    assert_eq!(exec_params.justification, justification);
    assert_eq!(exec_params.arg0, None);
}

#[test]
fn shell_handler_prepends_rtk_helper_dir_to_path() {
    let mut env = std::collections::HashMap::from([(
        "PATH".to_string(),
        "/usr/local/bin:/usr/bin".to_string(),
    )]);

    prepend_arg0_helper_dir_to_path(
        &mut env,
        Some(std::path::Path::new("/tmp/codex-arg0/codex-execve-wrapper")),
        None,
    );

    assert_eq!(
        env.get("PATH"),
        Some(&"/tmp/codex-arg0:/usr/local/bin:/usr/bin".to_string())
    );
}

#[test]
fn shell_command_handler_respects_explicit_login_flag() {
    let (_tx, shell_snapshot) = watch::channel(Some(Arc::new(ShellSnapshot {
        path: PathBuf::from("/tmp/snapshot.sh"),
        cwd: PathBuf::from("/tmp"),
    })));
    let shell = Shell {
        shell_type: ShellType::Bash,
        shell_path: PathBuf::from("/bin/bash"),
        shell_snapshot,
    };

    let login_command = ShellCommandHandler::base_command(&shell, "echo login shell", true);
    assert_eq!(
        login_command,
        shell.derive_exec_args("echo login shell", true)
    );

    let non_login_command =
        ShellCommandHandler::base_command(&shell, "echo non login shell", false);
    assert_eq!(
        non_login_command,
        shell.derive_exec_args("echo non login shell", false)
    );
}

#[tokio::test]
async fn shell_command_handler_defaults_to_non_login_when_disallowed() {
    let (session, turn_context) = make_session_and_context().await;
    let params = ShellCommandToolCallParams {
        command: "echo hello".to_string(),
        workdir: None,
        login: None,
        timeout_ms: None,
        sandbox_permissions: None,
        additional_permissions: None,
        prefix_rule: None,
        justification: None,
    };

    let exec_params = ShellCommandHandler::to_exec_params(
        &params,
        &session,
        &turn_context,
        session.conversation_id,
        false,
    )
    .expect("non-login shells should still be allowed");

    assert_eq!(
        exec_params.command,
        session.user_shell().derive_exec_args("echo hello", false)
    );
}

#[test]
fn shell_command_handler_rejects_login_when_disallowed() {
    let err = ShellCommandHandler::resolve_use_login_shell(Some(true), false)
        .expect_err("explicit login should be rejected");

    assert!(
        err.to_string()
            .contains("login shell is disabled by config"),
        "unexpected error: {err}"
    );
}

#[test]
fn shell_command_handler_routes_supported_commands_through_rtk() {
    assert_eq!(
        ShellCommandHandler::route_command("git status").command,
        "rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("head -20 src/main.rs").command,
        "rtk read src/main.rs --max-lines 20"
    );
    assert_eq!(
        ShellCommandHandler::route_command("command git status").command,
        "rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("command -p git status").command,
        "rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("git -C repo status").command,
        "rtk git -C repo status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("cargo --manifest-path Cargo.toml test -p codex-core")
            .command,
        "rtk cargo --manifest-path Cargo.toml test -p codex-core"
    );
    assert_eq!(
        ShellCommandHandler::route_command("cargo +nightly test -p codex-core").command,
        "rtk cargo '+nightly' test -p codex-core"
    );
    assert_eq!(
        ShellCommandHandler::route_command("git -c color.ui=always -C repo status").command,
        "rtk git -c color.ui=always -C repo status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("git --git-dir .git --work-tree . status").command,
        "rtk git --git-dir .git --work-tree . status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("nice -n 5 git status").command,
        "nice -n 5 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("stdbuf -oL git status").command,
        "stdbuf -oL rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("env --chdir=repo nice -n 5 git status").command,
        "env --chdir=repo nice -n 5 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("command nice -n 5 git status").command,
        "nice -n 5 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("command -p stdbuf -oL git status").command,
        "stdbuf -oL rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("command cargo +nightly test -p codex-core").command,
        "rtk cargo '+nightly' test -p codex-core"
    );
    assert_eq!(
        ShellCommandHandler::route_command("/usr/bin/nice -n 5 git status").command,
        "nice -n 5 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("ionice -c 3 git status").command,
        "ionice -c 3 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("command ionice -c2 git status").command,
        "ionice -c2 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("nice -n 5 ionice -c2 git status").command,
        "nice -n 5 ionice -c2 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("chrt -r 10 git status").command,
        "chrt -r 10 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("command chrt -b 0 git status").command,
        "chrt -b 0 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("nice -n 5 chrt -r 10 git status").command,
        "nice -n 5 chrt -r 10 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("codex rtk command -p stdbuf -oL git status").command,
        "stdbuf -oL rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command(
            "codex rtk env --chdir=repo command nice -n 5 git status"
        )
        .command,
        "env --chdir=repo nice -n 5 rtk git status"
    );
    assert_eq!(
        ShellCommandHandler::route_command("codex rtk env FOO=1 command grep \"a|b\" src/main.rs")
            .command,
        "env FOO=1 rtk grep 'a|b' src/main.rs"
    );
    assert_eq!(
        ShellCommandHandler::route_command(
            "codex rtk command nice -n 5 git log --format='%h|%s' -1"
        )
        .command,
        "nice -n 5 rtk git log '--format=%h|%s' -1"
    );
}

#[test]
fn shell_command_handler_leaves_compound_commands_raw() {
    let routed = ShellCommandHandler::route_command("git status | head");
    assert_eq!(routed.command, "git status | head");
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: git status | head\nexecuted: git status | head\nreason: contains compound shell syntax"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_reports_missing_command_after_prefixes() {
    let routed = ShellCommandHandler::route_command("env -i");
    assert_eq!(routed.command, "env -i");
    assert_eq!(routed.interaction_input, None);
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: env -i\nexecuted: env -i\nreason: missing command after prefixes"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_records_original_command_when_rewritten() {
    let routed = ShellCommandHandler::route_command("FOO=1 git status");
    assert_eq!(routed.command, "FOO=1 rtk git status");
    assert_eq!(
        routed.interaction_input,
        Some("FOO=1 git status".to_string())
    );
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command routed via embedded RTK]\noriginal: FOO=1 git status\nexecuted: FOO=1 rtk git status"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_reports_unsupported_wrapper_flags_as_raw() {
    let routed = ShellCommandHandler::route_command("env FOO=1 ionice -p 123 git status");
    assert_eq!(routed.command, "env FOO=1 ionice -p 123 git status");
    assert_eq!(routed.interaction_input, None);
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: env FOO=1 ionice -p 123 git status\nexecuted: env FOO=1 ionice -p 123 git status\nreason: command is not in the embedded RTK allowlist"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_reports_parse_failures_as_raw() {
    let routed = ShellCommandHandler::route_command("git 'unterminated");
    assert_eq!(routed.command, "git 'unterminated");
    assert_eq!(routed.interaction_input, None);
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: git 'unterminated\nexecuted: git 'unterminated\nreason: failed to parse shell words"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_routes_quoted_literals_but_blocks_real_shell_syntax() {
    let routed = ShellCommandHandler::route_command("grep 'a|b' src/main.rs");
    assert_eq!(routed.command, "rtk grep 'a|b' src/main.rs");
    assert_eq!(
        routed.interaction_input,
        Some("grep 'a|b' src/main.rs".to_string())
    );

    let double_quoted = ShellCommandHandler::route_command("grep \"a|b\" src/main.rs");
    assert_eq!(double_quoted.command, "rtk grep 'a|b' src/main.rs");

    let kept_raw = ShellCommandHandler::route_command("grep \"$(pwd)\" src/main.rs");
    assert_eq!(kept_raw.command, "grep \"$(pwd)\" src/main.rs");
    assert_eq!(
        kept_raw.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: grep \"$(pwd)\" src/main.rs\nexecuted: grep \"$(pwd)\" src/main.rs\nreason: contains compound shell syntax"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_normalizes_codex_rtk_help_commands() {
    let routed = ShellCommandHandler::route_command("codex rtk --help");
    assert_eq!(routed.command, "rtk --help");
    assert_eq!(
        routed.interaction_input,
        Some("codex rtk --help".to_string())
    );
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command routed via embedded RTK]\noriginal: codex rtk --help\nexecuted: rtk --help"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_keeps_codex_rtk_compounds_raw() {
    let routed = ShellCommandHandler::route_command("codex rtk git status | head");
    assert_eq!(routed.command, "codex rtk git status | head");
    assert_eq!(routed.interaction_input, None);
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: codex rtk git status | head\nexecuted: codex rtk git status | head\nreason: contains compound shell syntax"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_keeps_sudo_commands_raw_even_with_prefixes() {
    let routed = ShellCommandHandler::route_command("env FOO=1 sudo git status");
    assert_eq!(routed.command, "env FOO=1 sudo git status");
    assert_eq!(routed.interaction_input, None);
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: env FOO=1 sudo git status\nexecuted: env FOO=1 sudo git status\nreason: sudo commands are never auto-routed"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_keeps_codex_rtk_passthrough_matrix_raw() {
    let unsupported_args = ShellCommandHandler::route_command("codex rtk tail -f src/main.rs");
    assert_eq!(unsupported_args.command, "codex rtk tail -f src/main.rs");
    assert_eq!(
        unsupported_args.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: codex rtk tail -f src/main.rs\nexecuted: codex rtk tail -f src/main.rs\nreason: command shape is not supported by the embedded RTK rewriter"
                .to_string()
        )
    );

    let missing = ShellCommandHandler::route_command("codex rtk env -i");
    assert_eq!(missing.command, "codex rtk env -i");
    assert_eq!(
        missing.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: codex rtk env -i\nexecuted: codex rtk env -i\nreason: missing command after prefixes"
                .to_string()
        )
    );

    let unsupported = ShellCommandHandler::route_command("codex rtk command chrt -m git status");
    assert_eq!(unsupported.command, "codex rtk command chrt -m git status");
    assert_eq!(
        unsupported.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: codex rtk command chrt -m git status\nexecuted: codex rtk command chrt -m git status\nreason: command is not in the embedded RTK allowlist"
                .to_string()
        )
    );
}

#[test]
fn shell_command_handler_keeps_codex_rtk_shell_syntax_raw() {
    let routed = ShellCommandHandler::route_command("codex rtk grep \"$(pwd)\" src/main.rs");
    assert_eq!(routed.command, "codex rtk grep \"$(pwd)\" src/main.rs");
    assert!(matches!(
        routed.model_output_prefix.as_deref(),
        Some(prefix) if prefix.contains("contains compound shell syntax")
    ));
}

#[test]
fn shell_command_handler_leaves_unsupported_read_shapes_raw() {
    let routed = ShellCommandHandler::route_command("tail -f src/main.rs");
    assert_eq!(routed.command, "tail -f src/main.rs");
    assert_eq!(
        routed.model_output_prefix,
        Some(
            "[shell_command kept raw]\noriginal: tail -f src/main.rs\nexecuted: tail -f src/main.rs\nreason: command shape is not supported by the embedded RTK rewriter"
                .to_string()
        )
    );
}

#[tokio::test]
async fn snapshot_explicit_env_overrides_keep_helper_path() {
    let (_session, mut turn_context) = make_session_and_context().await;
    turn_context
        .shell_environment_policy
        .r#set
        .insert("FOO".to_string(), "bar".to_string());

    let dependency_env = HashMap::from([("OPENAI_API_KEY".to_string(), "secret".to_string())]);
    let exec_env = HashMap::from([
        (
            "PATH".to_string(),
            "/tmp/codex-arg0-helper:/usr/local/bin:/usr/bin".to_string(),
        ),
        ("OPENAI_API_KEY".to_string(), "secret".to_string()),
    ]);

    let overrides = crate::exec_env::explicit_snapshot_env_overrides(
        &turn_context.shell_environment_policy.r#set,
        &dependency_env,
        &exec_env,
    );

    assert_eq!(
        overrides.get("PATH"),
        Some(&"/tmp/codex-arg0-helper:/usr/local/bin:/usr/bin".to_string())
    );
    assert_eq!(overrides.get("FOO"), Some(&"bar".to_string()));
    assert_eq!(overrides.get("OPENAI_API_KEY"), Some(&"secret".to_string()));
}
